version: '3.7'
#v5
services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    shell: echo "secret variable is ${TEST_VAR}"
    volumes:
      - static:/static
    ports:
      - "234:80"
    depends_on:
      - django_gunicorn

volumes:
  static:


