version: '3.7'
#v4
services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - shell: echo "Environment ----> is ${env}"
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "234:80"
    depends_on:
      - django_gunicorn

volumes:
  static:

